const CREATED_STATUS = 201;
const REQUEST_ERROR = 400;
const SERVER_ERROR = 500;
const UNAUTHORIZED_ERROR = 401;
const NOT_FOUND_ERROR = 404;
const MESSAGE_SERVER_ERROR = 'На сервере произошла ошибка';
const MESSAGE_REQUEST_ERROR = 'Переданы некорректные данные';
const MESSAGE_NOT_FOUND_ERROR = 'Информация не найдена';
const MESSAGE_UNAUTHORIZED_ERROR = 'Неправильные почта или пароль';
const MESSAGE_AUTHENTICATION_ERROR = 'Необходима авторизация';

module.exports = {
  CREATED_STATUS,
  REQUEST_ERROR,
  SERVER_ERROR,
  UNAUTHORIZED_ERROR,
  NOT_FOUND_ERROR,
  MESSAGE_SERVER_ERROR,
  MESSAGE_REQUEST_ERROR,
  MESSAGE_NOT_FOUND_ERROR,
  MESSAGE_UNAUTHORIZED_ERROR,
  MESSAGE_AUTHENTICATION_ERROR,
};
